
INSERT INTO states(id,name,short) VALUES ('01','Aguascalientes','Ags.');
INSERT INTO states(id,name,short) VALUES ('02','Baja California','BC');
INSERT INTO states(id,name,short) VALUES ('03','Baja California Sur','BCS');
INSERT INTO states(id,name,short) VALUES ('04','Campeche','Camp.');
INSERT INTO states(id,name,short) VALUES ('05','Coahuila de Zaragoza','Coah.');
INSERT INTO states(id,name,short) VALUES ('06','Colima','Col.');
INSERT INTO states(id,name,short) VALUES ('07','Chiapas','Chis.');
INSERT INTO states(id,name,short) VALUES ('08','Chihuahua','Chih.');
INSERT INTO states(id,name,short) VALUES ('09','Distrito Federal','DF');
INSERT INTO states(id,name,short) VALUES ('10','Durango','Dgo.');
INSERT INTO states(id,name,short) VALUES ('11','Guanajuato','Gto.');
INSERT INTO states(id,name,short) VALUES ('12','Guerrero','Gro.');
INSERT INTO states(id,name,short) VALUES ('13','Hidalgo','Hgo.');
INSERT INTO states(id,name,short) VALUES ('14','Jalisco','Jal.');
INSERT INTO states(id,name,short) VALUES ('15','México','Mex.');
INSERT INTO states(id,name,short) VALUES ('16','Michoacán de Ocampo','Mich.');
INSERT INTO states(id,name,short) VALUES ('17','Morelos','Mor.');
INSERT INTO states(id,name,short) VALUES ('18','Nayarit','Nay.');
INSERT INTO states(id,name,short) VALUES ('19','Nuevo León','NL');
INSERT INTO states(id,name,short) VALUES ('20','Oaxaca','Oax.');
INSERT INTO states(id,name,short) VALUES ('21','Puebla','Pue.');
INSERT INTO states(id,name,short) VALUES ('22','Querétaro','Qro.');
INSERT INTO states(id,name,short) VALUES ('23','Quintana Roo','Q. Roo');
INSERT INTO states(id,name,short) VALUES ('24','San Luis Potosí','SLP');
INSERT INTO states(id,name,short) VALUES ('25','Sinaloa','Sin.');
INSERT INTO states(id,name,short) VALUES ('26','Sonora','Son.');
INSERT INTO states(id,name,short) VALUES ('27','Tabasco','Tab.');
INSERT INTO states(id,name,short) VALUES ('28','Tamaulipas','Tamps.');
INSERT INTO states(id,name,short) VALUES ('29','Tlaxcala','Tlax.');
INSERT INTO states(id,name,short) VALUES ('30','Veracruz de Ignacio de la Llave','Ver.');
INSERT INTO states(id,name,short) VALUES ('31','Yucatán','Yuc.');
INSERT INTO states(id,name,short) VALUES ('32','Zacatecas','Zac.');
INSERT INTO states(id,name,short) VALUES ('CVE_ENT','NOM_ENT','NOM_ABR');
